ALIVE = "ALIVE_IMG = "https://telegra.ph/file/5fbacbbc038bb7fac6704.jpg" 
ALIVE_caption = "`FRIDAY IS:` **ONLINE**\n\n"
ALIVE_caption += "**SYSTEM STATUS**\n\n"
ALIVE_caption += "`TELETHON VERSION:` **6.0.9**\n`Python:` **3.7.4**\n\n"
ALIVE_caption += "`DATABASE STATUS:` **Functional**\n\n"
ALIVE_caption += "**Current Branch** : `master`\n\n"
ALIVE_caption += "**Friday OS** : `3.14`\n\n"
ALIVE_caption += "**Current Sat** : `StarkGangSat-2.25`\n\n"
ALIVE_caption += f"**My Boss** : {DEFAULTUSER} \n\n"
ALIVE_caption += "**Heroku Database** : `AWS - Working Properly`\n\n"
ALIVE_caption += "**License** : [MIT Licence](github.com/StarkGang/FridayUserbot/blob/master/LICENSE)\n\n"
ALIVE_caption += "Copyright By [StarkGang@Github](GitHub.com/StarkGang)\n\n"
ALIVE_caption += "[Deploy FridayUserbot](https://telegra.ph/FRIDAY-06-15)""
